# You can change this list with the same as the one that you use for the web scraping feature
school_list = ['Alliant International University', 'American Heritage University of Southern California',
               'American Jewish University', 'Andrews University', 'ArtCenter College of Design', 'Barnard College',
                'Berklee College of Music', 'Biola University', 'Boston College', 'Boston University', 'Bowdoin College','Brandeis University',
               'Brown University', 'California Institute of Integral Studies', 'California Institute of Technology',
               'California Institute of the Arts', 'California Lutheran University', 'California Miramar University',
               'California Polytechnic State University, Pomona', 'California South Bay University',
                'California State University Channel Islands',
               'California State University San Marcos', 'California State University, Bakersfield',
               'California State University, Chico', 'California State University, East Bay',
               'California State University, Fresno', 'California State University, Fullerton',
               'California State University, Los Angeles', 'California State University, Monterey Bay',
               'California State University, Northridge', 'California State University, Sacramento',
               'California State University, San Bernardino', 'California State University, Stanislaus',
               'Cambridge College', 'Carnegie Mellon University', 'Case Western Reserve University',
               'Chapman University', 'Charles R. Drew University of Medicine and Science',
               'Claremont Graduate University', 'Claremont McKenna College', 'Colby College', 'Colgate University','College of the Holy Cross',
               'Columbia University', 'Concordia University Irvine', 'Cornell University', 'Dartmouth College',
                'Dominican University of California', 'Drexel University',
               'Duke University', 'Eckerd College','Emory University',  'Florida State University',
               'George Mason University', 'George Washington University','Georgetown University', "Georgia Institute of Technology",
               'Graduate Theological Union', 'Grinnell College','Hamilton College','Harvard University', 'Harvey Mudd College', 'Haverford College','Holy Names University',
               'Howard University', 'Humphreys University', 'Illinois Institute of Technology',
               'Indiana University Bloomington', 'Johns Hopkins University', 
               'La Sierra University',
                'Laguna College of Art and Design', 'Lehigh University',
               'Loyola Marymount University', 'Menlo College',
               'Michigan State University', 'Middlebury College', 'Morehouse College','National University', 'New York University','North Carolina State University',
               'Northeastern University', 'Northwestern Polytechnic University', 'Northwestern University',
               'Notre Dame de Namur University', 'Oak Valley College', 'Oberlin College','Occidental College', 
               #'Oikos University',
               'Otis College of Art and Design', 'Pacific Lutheran Theological Seminary', 'Pacific Oaks College',
               'Pacific School of Religion', 'Pacific Union College', 'Pacifica Graduate Institute',
                'Pennsylvania State University', 'Pepperdine University', 'Pitzer College', 'Point Loma Nazarene University',
               'Pomona College', 'Princeton University', 'Providence Christian College', 'Purdue University',
               'Rensselaer Polytechnic Institute', 'Rhode Island School of Design','Rice University', 'Rutgers University', "Saint Mary's College of California",
               'Samuel Merritt University', 'San Diego Christian College', 'San Diego State University',
               'San Francisco State University', 'San Joaquin College of Law', 'Santa Clara University',
               'Saybrook University', 'Scripps College', 'Simpson University', 'Smith College','Soka University of America',
               'Sonoma State University', 'Southern Methodist University', 'Southwestern Law School',
               'Stanford University', 'Swathmore College','Syracuse University', 'Temple University', 'Texas A&M University', 'The College of New Jersey'
               "The Master's University", 'The New School','Thomas Aquinas College', 'Touro University California', 'Tufts University',
               'Tulane University', 'University of Antelope Valley', 'University of California, Irvine','University of California, Los Angeles','University of Chicago','University of Colorado Boulder', 'University of Colorado Denver','University of Connecticut',
               'University of Denver', 'University of Florida', 'University of Hawaii at Manoa',
               'University of Houston', 'University of Kentucky','University of La Verne', 'University of Louisville',
               'University of Maryland, Baltimore County', 'University of Massachusetts Amherst', 'University of Miami',
               'University of Michigan', 'University of North Carolina at Chapel Hill', 'University of Notre Dame', 'University of Oregon',
               'University of Pennsylvania', 'University of Pittsburgh', 'University of Redlands',
               'University of Rochester', 'University of San Diego', 'University of San Francisco',
               'University of Southern California', 'University of Texas at Austin', 'University of Vermont','University of Virginia',
               'University of Washington', 'University of West Los Angeles', 'University of Wisconsin-Madison',
               'University of the Pacific', 'University of the People', 'University of the West', 'Ursinus College',
               'Vanderbilt University', 'Vanguard University', 'Vassar College','Virginia Commonwealth University',
               'Wake Forest University', 'Washington University in St. Louis', 'Wesleyan University', 'Westcliff University',
               'Western State College of Law', 'Western University of Health Sciences', 'Westmont College',
               'Whittier College', 'Woodbury University', 'Worcester Polytechnic Institute', 'Yale University',
               'Zaytuna College']

